name: Ruff Autofix
on: [pull_request]
jobs:
  ruff:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          args: --fix -e
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: ruff

